export const PRODUCT_ATTRIBUTE_REPOSITORY = Symbol('PRODUCT_ATTRIBUTE_REPOSITORY');
export const SET_PRODUCT_ATTRIBUTES_USE_CASE = Symbol('SET_PRODUCT_ATTRIBUTES_USE_CASE');
export const UPDATE_PRODUCT_ATTRIBUTES_USE_CASE = Symbol('UPDATE_PRODUCT_ATTRIBUTES_USE_CASE');
export const FIND_PRODUCT_ATTRIBUTES_USE_CASE = Symbol('FIND_PRODUCT_ATTRIBUTES_USE_CASE');
