export const CREATE_ORDER_USE_CASE = Symbol('CREATE_ORDER_USE_CASE');
export const GET_ORDERS_USE_CASE = Symbol('GET_ORDERS_USE_CASE');
export const UPDATE_ORDER_STATUS_USE_CASE = Symbol('UPDATE_ORDER_STATUS_USE_CASE');
