services:
  postgres:
    image: postgres:15
    container_name: neohw_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: neohw_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: neohw_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
