export const ATTRIBUTE_REPOSITORY = Symbol('ATTRIBUTE_REPOSITORY');
export const CREATE_ATTRIBUTE_USE_CASE = Symbol('CREATE_ATTRIBUTE_USE_CASE');
export const FIND_ALL_ATTRIBUTES_USE_CASE = Symbol('FIND_ALL_ATTRIBUTES_USE_CASE');
export const FIND_ATTRIBUTES_BY_CATEGORY_USE_CASE = Symbol('FIND_ATTRIBUTES_BY_CATEGORY_USE_CASE');
export const UPDATE_ATTRIBUTE_USE_CASE = Symbol('UPDATE_ATTRIBUTE_USE_CASE');
export const ASSIGN_ATTRIBUTE_TO_CATEGORY_USE_CASE = Symbol('ASSIGN_ATTRIBUTE_TO_CATEGORY_USE_CASE');
