export const COMPATIBILITY_REPOSITORY = Symbol('COMPATIBILITY_REPOSITORY');
export const PRODUCT_ATTRIBUTES_FETCHER = Symbol('PRODUCT_ATTRIBUTES_FETCHER');
export const COMPATIBILITY_ENGINE = Symbol('COMPATIBILITY_ENGINE');
export const CHECK_COMPATIBILITY_USE_CASE = Symbol('CHECK_COMPATIBILITY_USE_CASE');
export const CREATE_COMPATIBILITY_RULE_USE_CASE = Symbol('CREATE_COMPATIBILITY_RULE_USE_CASE');
export const FIND_ALL_RULES_USE_CASE = Symbol('FIND_ALL_RULES_USE_CASE');
export const DELETE_RULE_USE_CASE = Symbol('DELETE_RULE_USE_CASE');
