export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const CHANGE_USER_ROLE_USE_CASE = Symbol('CHANGE_USER_ROLE_USE_CASE');
export const FIND_ALL_USERS_USE_CASE = Symbol('FIND_ALL_USERS_USE_CASE');
export const UPDATE_USER_USE_CASE = Symbol('UPDATE_USER_USE_CASE');
export const SOFT_DELETE_USER_USE_CASE = Symbol('SOFT_DELETE_USER_USE_CASE');
