export const PRODUCT_REPOSITORY = Symbol('PRODUCT_REPOSITORY');
export const CREATE_PRODUCT_USE_CASE = Symbol('CREATE_PRODUCT_USE_CASE');
export const FIND_ALL_PRODUCTS_USE_CASE = Symbol('FIND_ALL_PRODUCTS_USE_CASE');
export const FIND_PRODUCT_BY_ID_USE_CASE = Symbol('FIND_PRODUCT_BY_ID_USE_CASE');
export const UPDATE_PRODUCT_USE_CASE = Symbol('UPDATE_PRODUCT_USE_CASE');
export const DELETE_PRODUCT_USE_CASE = Symbol('DELETE_PRODUCT_USE_CASE');
