export const CATEGORY_REPOSITORY = Symbol('CATEGORY_REPOSITORY');
export const CREATE_CATEGORY_USE_CASE = Symbol('CREATE_CATEGORY_USE_CASE');
export const FIND_ALL_CATEGORIES_USE_CASE = Symbol('FIND_ALL_CATEGORIES_USE_CASE');
export const FIND_CATEGORY_BY_ID_USE_CASE = Symbol('FIND_CATEGORY_BY_ID_USE_CASE');
export const UPDATE_CATEGORY_USE_CASE = Symbol('UPDATE_CATEGORY_USE_CASE');
export const DELETE_CATEGORY_USE_CASE = Symbol('DELETE_CATEGORY_USE_CASE');
